"""empty message

Revision ID: 0adb05e41e58
Revises: 
Create Date: 2018-08-06 21:12:22.828103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0adb05e41e58'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Object',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Node',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['Object.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subtype', sa.String(), nullable=True),
    sa.Column('distance', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('destination_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['Node.id'], ),
    sa.ForeignKeyConstraint(['id'], ['Object.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['Node.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Fiber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['Link.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Traffic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['Link.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Traffic')
    op.drop_table('Fiber')
    op.drop_table('Link')
    op.drop_table('Node')
    op.drop_table('Object')
    # ### end Alembic commands ###
